### ISSUE TITLE
OperationalError at /admin/joyride/joyridehistory/add/ no such table: joyride_joyride

### ISSUE THREAD

**Issue by teolemon** [intellisense/django-joyride#5]
When trying to add a Joyride History (nb:without having added a Joyride first, but after doing the proper syncdb and migrate), using http://127.0.0.1:8000/admin/joyride/joyridehistory/add/
I get the following which says the table doesn't exist.

OperationalError at /admin/joyride/joyridehistory/add/
no such table: joyride_joyride
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/joyride/joyridehistory/add/
Django Version:	1.6.5
Exception Type:	OperationalError
Exception Value:	
no such table: joyride_joyride

18	                        {% else %}
19	                            {{ field.field }}
20	                        {% endif %}

**Comment by intellisense** [comment]
You must be doing something wrong. The latest release is well tested and everything works as expected. Are you sure you have put `joyride` in `INSTALLED_APPS`?

**Comment by intellisense** [comment]
Probably it is in  `INSTALLED_APPS` as you are seeing it in admin. Can you please do `syncdb` again, and make sure to check your database to verify the table is there?
